chrchang/plink-ng

- plink.c
* Due to subtle bug, the program accepts undefined commands like `--pe` as `--perm-batch-size`.
* Just fixed wrong command length for `memcmp`.
```
% plink --pe -1
PLINK v1.90b3p 64-bit (27 Aug 2014)        https://www.cog-genomics.org/plink2
(C) 2005-2014 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to plink.log.
Error: Invalid --perm-batch-size parameter '-1'.
For more information, try 'plink --help [flag name]' or 'plink --help | more'.
```
> Fix parse error of `perm-batch-size`

- plink_glm.c
* Since `glm_common_init` returns `RET_SUCCESS` to `glm_linear_assoc`/`glm_logistic_assoc` when it skips, the program shows an incorrect "Out of memory" error message.
* Just moved the validation code into each assoc function.
* For usability, it might be better to warn "less than two phenotypes are present", like `--assoc`/`--model` do (9f9c305).
```
% plink --file toy --logistic
PLINK v1.90b3a 64-bit (12 Jan 2015)        https://www.cog-genomics.org/plink2
(C) 2005-2015 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to plink.log.
96695 MB RAM detected; reserving 48347 MB for main workspace.
.ped scan complete (for binary autoconversion).
Performing single-pass .bed write (2 variants, 2 people).
--file: plink-temporary.bed + plink-temporary.bim + …
```
> Fix incorrect error message of `--linear`/`--logistic` when # variables >= # samples

- plink.c
- plink_filter.c
- plink_filter.h
* I wanted to randomly sample individuals, so I added `--thin-indiv` and `--thin-indiv-count` commands likewise `--thin` and `--thin-count`.
* Although I'm not sure there are general needs, I think it might be useful for some that PLINK has symmetric functionality for random sampling of variants/individuals.
https://www.cog-genomics.org/plink2/order
...
* Filter based on sex, phenotype, and/or founder status (`--filter-males`...)
* **Random thinning of sample set (`--thin-indiv`, `--thin-indiv-count`)**
* Calculate per-sample genotyping rate, remove samples below threshold (`--mind`)
> Add --thin-indiv and --thin-indiv-count commands

- plink_data.c
For a VCF called with GATK 3.4, if the first ALT allele is "\*", PLINK would previously fail with "invalid alternate allele".  This patch allows the 1st character of the ALT allele string to be "\*".
> Allow for GATK3.4 *:DEL-alleles

- Makefile.std
- plink_assoc.c
- Fixed double free bug in `gxe_assoc()` that was causing crashes in Linux.
- Modified Makefile to support parallel builds (i.e., `make -jN`), a `clean` target, and additional linker options via the `LINKFLAGS_EXTRA` variable. *NOTE*: the modified Makefile has been tested on Linux and OS X, but _not_ in Windows (since I don't currently have access to it); however, the modifications should work as long as the `make` being used is GNU make compatible.
> Double free error and Makefile fixes

- 2.0/Python/setup.py
This pull request switches from `distutils` to `setuptools` in `setup.py` for Pgenlib. The main advantage of switching is that one can more easily create `egg` or `wheel` packages for saving on private Python package repos.
> Switched from distutils to setuptools in Pgenlib

- 1.9/plink_first_compile
This PR changes the first-compile script to use the standard Makefile. This suppresses a link error because the old Makefile tries to build using some old 32-bit headers.
> Change the first-compile script to use the standard Makefile

- 1.9/Makefile.std
The Debian package needs this flags to inject some hardening options.
https://anonscm.debian.org/cgit/debian-med/plink1.9.git/tree/debian/patches/01.Fix_Makefile.patch
> Take into account the user-provided CPPFLAGS compiler flags

- 1.9/plink.c
- 1.9/plink_ld.c
For some work that I'm doing it is necessary to calculate a large number of tag SNPs using the `--r` function, but this is problematic as it is slow and creates a huge output as there is no flag to limit the output based on magnitude of LD.
In this commit I have simply allowed `--ld-window-r2` to be used with both `--r` and `--r2`, which extends the behaviour to how it was previously when it only worked for `--r2`. The interpretation to the user is that if the supply the `--r --ld-window-r2 <val>` then the threshold will be set at `abs(r) > sqrt(<val>))`.
Previously it seems the default behaviour was to print every LD value for `--r`. Now the default will be the same as the default for `--r2` which is to only print anything with `r2 > 0.2`.
> allowing --ld-window-r2 flag for --r

- .gitmodules
- 2.0/Makefile
- 2.0/build_dynamic/Makefile
- 2.0/include/SFMT.h
- 2.0/include/plink2_base.h
- 2.0/plink2.cc
- 2.0/plink2_glm.cc
Hello again. This is another patch from the Debian package of plink2. It enables building on non-x86 architectures link arm64, ppc64el, s390x, and more: https://buildd.debian.org/status/package.php?p=plink2
This also allows us to compile plink on x86 systems without advanced SIMD usage, as that is required by the Debian x86 64 and 32 bit architecture baselines. On x86 we make several plink2 binaries using the `SFX` shown below. At runtime a dispatcher script selects the most capable binary for the user's CPU.
You can see our compile recipe at https://salsa.debian.org/med-team/plink2/-/blob/master/debian/rules#L36 and the dispatcher script at https://salsa.debian.org/med-team/plink2/-/blob/master/debian/bin/simd-dispatch
If a CPU dispatcher was integrated into plink2 then this external …
> enable building on non-x86 systems

- 2.0/plink2_glm.cc
- 2.0/plink2_ld.cc
Setting with `{}` is a gcc-ism and is non-standard
> Portable __m128i and __m256i setting

- 1.9/tests/tests.py
`sys.exit(1)` can be easily replaced with the underlying code that it implies. `sys.exit()` implies `raise SystemExit` while `sys.exit(1)` implies `raise SystemExit(1)`. This does not change the functionality of the tests, but instead cuts down tests runtime by a marginal amount.
> Change Test's Exit Structure

- 1.9/plink.c
- 1.9/plink_glm.c
Trivially resolves array-bounds and stringop-overflow warnings.
> Resolves array-bounds and stringop-overflow warnings

- 1.9/plink_ld.c
The warning was thrown at line 3392 of the original code for lambda_or_mu[0] and was caused by the compiler not noticing that group_ct can be either 1 or 2. This same issue caused the warning about tot_inv_v[0] that has been previously fixed by initializing it to zero. 
The issue is here resolved by adding an 'if' clause, because it seemed the least intrusive. The initialization of tot_inv_v[0] to zero was removed because the fix made it redundant.
Tested on both centos7 with devtoolset-7 (gcc 7.3.1) and fedora33 with gcc 10.2.1.
> Fixes maybe-uninitialized warning thown in line 3392 (now 3399).

- .github/workflows/can_install_pgenlib_package.yaml
Hi @chrchang,
Following #204. in which I submitted a bug report that `pgenlib` could not be installed, here is a GitHub Actions that helps to prevent this in the future: in the default GitHub Actions settings, the owner of the repo will receive an email if the build breaks (of course, this can be turned off). 
I kept this PR minimal, e.g. I did not add a GHA build badge [1], but volunteer to add that as well.
Thanks for allowing PLINK to show off its quality and cheers, Richel
* [1] An example build badge (just the image, it has no clickable link):
> GitHub Actions checks if `pgenlib` can be installed

- 1.9/Makefile
Add conditional logic to link to the correct static libz on apple silicon arm64 CPU on Mac OS.
As documented [here](https://github.com/chrchang/plink-ng/issues/162), this is the minimum changeset necessary to allow Plink 1.9 to work with Apple Silicon.
It looks like 2.0 will take a bit more work.
> Allow Plink 1.9 to compile & run on Apple Silicon 

- 2.0/include/plink2_base.h
- 2.0/include/plink2_bits.cc
- 2.0/plink2.cc
- 2.0/plink2_export.cc
Replace the functions that wrap simde with macros, allowing them to work on ARM NEON. NEON requires that bit-shifting instructions are called with constant integers. This lets plink2.0 build on Apple Silicon on MacOS.
I changed the inline functions into macros, which is definitely more fragile and nastier to debug, but otherwise compilation would fail because the underlying NEON intrinsics could only be called with constant integers for the offset, meaning they can't be called from a function that takes runtime parameters. Where there were dynamic calls to these functions, I added a lookup table that will map to the function called with a compile-time constant. This doesn't feel great, but gets Plink2 running on Apple Silicon. I have not yet tested it extensively, but it runs.
I don't …
> Fix Plink2 build on Apple Silicon MacOS: Call NEON SIMD instructions with constants.

- 2.0/Python/README.md
Update installation instructions for python to accommodate less experienced users.
It would also be ideal to add a hyperlink to the [documentation](https://www.cog-genomics.org/plink/2.0/), mentioning the python package (I end up spending a bit of time finding my way here).
> Update installation instructions for python

- 2.0/Python/pyproject.toml
Hi @chrchang,
Our team uses `pgenlib` and noticed an intermittent issue when installing it with `pip`. We've found that a binary incompatibility can occur when the version of `numpy` used to build `pgenlib` is newer than the version used when running `pgenlib`. We think the solution is to list the `oldest-supported-numpy` package as a build-time dependency instead of `numpy`.
See [the README for `oldest-supported-numpy`](https://pypi.org/project/oldest-supported-numpy/) and [the numpy documentation](https://numpy.org/doc/stable/user/depending_on_numpy.html#build-time-dependency) for more information on why this is advisable.
See https://github.com/CAST-genomics/haptools/issues/138 for our example instance of a binary incompatibility and a more detailed explanation of our problem in plain …
> list `oldest-supported-numpy` as a build dependency

- 2.0/pgenlibr/src/Makevars.in
- 2.0/pgenlibr/src/install.libs.R
I'm writing a R package with an Rcpp package, and I'd like to access the plink code at the C++ level.  You made some small changes before based on this (https://github.com/chrchang/plink-ng/issues/283), and here I make two small changes so C++ code in other packages can access plink code at compile time.
1) Modify `Makevars.in` to include `pvar_ffi_support.o` and `pgenlib_ffi_support.o` in `libPLINK2.a`
2) Add `install.libs.R` to put static libraries in the default install path, so C++ in other packages can link against them.
In testing, this works on OSX and linux
> add ffi and install.libs.R

- .github/workflows/release.yaml
- 2.0/Python/pyproject.toml
Sorry for the noise, @chrchang
Here's one more change to the release.yaml workflow to 1) upgrade to the latest `cibuildwheel` to allow py3.13 wheels to be built and to 2) workaround the pypy issue that you mentioned here:
https://github.com/chrchang/plink-ng/blob/8671e46090a987a35f100d82cd301eb5a9682a86/2.0/manylinux-build-wheels.sh#L14-L15
I tested this on my fork and was able to build all of the wheels:
https://github.com/aryarm/plink-ng/actions/runs/15167833912
Also, I noticed that the latest 0.92.0 is missing wheels for aarch64 and some others?
https://pypi.org/project/Pgenlib/0.92.0/#files
https://pypi.org/project/Pgenlib/0.91.0/#files
If that's because of something that is wrong with the workflow, please let me know! I'm always happy to fix it
> ci: enable py3.13 wheels and workaround pypy issue
